<?php

namespace App\Providers;

// use Illuminate\Support\Facades\Gate;
use Illuminate\Foundation\Support\Providers\AuthServiceProvider as ServiceProvider;
use Illuminate\Support\Facades\Gate;
use function Symfony\Component\Translation\t;

class AuthServiceProvider extends ServiceProvider
{
    /**
     * The model to policy mappings for the application.
     *
     * @var array<class-string, class-string>
     */
    protected $policies = [
        //
//        'App\Models\Product' => 'App\Policies\ModelPolicy',
//        'App\Models\Role' => 'App\Policies\ModelPolicy',
//        'App\Models\Category' => 'App\Policies\ModelPolicy',
    ];

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
        $this->app->bind('abilities',function () {
            return include base_path('data/abilities.php');
        });
    }

    /**
     * Register any authentication / authorization services.
     */
    public function boot(): void
    {
        $this->registerPolicies();


        Gate::before(function ($user,$ability){
           if ($user->super_admin){
               return true;
           }
        });

        foreach ($this->app->make('abilities') as $code =>$lable){
            Gate::define($code,function ($user) use ($code){
                return $user->HasAbility($code);
            });
        }
    }
}
